name: moatmat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.25.4
  firebase_dynamic_links: ^5.4.13
  flick_video_player: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.2
  flutter_staggered_animations: ^1.1.1
  flutter_windowmanager: ^0.2.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  # qr_flutter: ^4.1.0
  rename: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.3.1
  uni_links: ^0.5.1
  url_launcher: ^6.2.4
  video_player: ^2.8.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/fonts/Tajawal/
    - assets/images/
    - assets/audios/
    - assets/images/home/
    - assets/images/apps/
    - assets/images/materials/
    - assets/images/start/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 700
