name: moatmat_app
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.2+108
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  audioplayers: ^6.1.0
  better_player_plus: ^1.0.8
  cached_network_image: ^3.4.1
  chewie: ^1.11.3
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^11.4.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_dynamic_links: ^6.0.8
  firebase_messaging: ^15.2.7
  flick_video_player: ^0.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cached_pdfview: ^0.4.2
  flutter_local_notifications: ^19.3.0
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.12
  get_it: ^8.0.0
  google_sign_in: ^6.3.0
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.20.2
  no_screenshot: ^0.3.1
  package_info_plus: ^8.3.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.0+1
  qr_code_scanner_plus: ^2.0.6
  qr_flutter: ^4.1.0
  rename: ^3.0.1
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.6.0
  timeago: ^3.7.1
  url_launcher: ^6.3.0
  video_player: ^2.8.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/fonts/Tajawal/
    - assets/images/
    - assets/audios/
    - assets/images/home/
    - assets/images/apps/
    - assets/images/materials/
    - assets/images/start/
    - assets/images/centers/
    - assets/images/teachers/
    - assets/images/boarding/
    - assets/images/governorates/
    - assets/images/auth/
    - assets/images/tests/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 700
