// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5LMbJetPa9b4p9nTaGAPkrEz0U73z0oE',
    appId: '1:359748080763:android:415c21cbf0e3b3516dbede',
    messagingSenderId: '359748080763',
    projectId: 'moatmat-project',
    storageBucket: 'moatmat-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzr5yweozr9Apx15ve130_A8A3unnOIpU',
    appId: '1:359748080763:ios:22046be4c15709016dbede',
    messagingSenderId: '359748080763',
    projectId: 'moatmat-project',
    storageBucket: 'moatmat-project.appspot.com',
    androidClientId: '359748080763-7vl5ubi4o48g5t625c1dkaul80e9q130.apps.googleusercontent.com',
    iosClientId: '359748080763-81e9q7f7e49a9lqsi157jed7f38rht0h.apps.googleusercontent.com',
    iosBundleId: 'com.moatmat.app',
  );

}